### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Sanskar-Choubey**

### CODE REVIEW

**Review by arp99 — CHANGES_REQUESTED** [review]
Looks fine , but the toast is not showing properly in the side navigation
toast-error

**Review by arp99 — APPROVED** [review]
Looks good now

**Comment by Sanskar-Choubey** [comment]
> Looks good now

Thanks for the feedback though

**Review by RawHeatG — COMMENTED** [review]
1.) The :hover on the green button breaks as the color-changing is the same as the previous color
2.) Add a little padding in the bottom of dismiss card
3.) Validation and Error Styled Input, the icon used has a different background the background color, same background icon will blend in
4.) add some padding at the end of the page, not able to scroll to the bottom of the page

**Comment by Sanskar-Choubey** [comment]
> 1.) The :hover on the green button breaks as the color-changing is the same as the previous color
> 2.) Add a little padding in the bottom of dismiss card
> 3.) Validation and Error Styled Input, the icon used has a different background the background color, same background icon will blend in
> 4.) add some padding at the end of the page, not able to scroll to the bottom of the page

**Comment by Sanskar-Choubey** [comment]
Thanks for the valuable feedback.Made all the suggested changes please check.

**Pull request merged**
